--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Ubuntu 17.4-1.pgdg22.04+2)
-- Dumped by pg_dump version 17.4 (Ubuntu 17.4-1.pgdg22.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: language; Type: TYPE; Schema: public; Owner: akul
--

CREATE TYPE public.language AS ENUM (
    'ENGLISH',
    'TAMIL',
    'TELEGU'
);


ALTER TYPE public.language OWNER TO akul;

--
-- Name: language_enum; Type: TYPE; Schema: public; Owner: akul
--

CREATE TYPE public.language_enum AS ENUM (
    'TAMIL',
    'ENGLISH',
    'TELEGU'
);


ALTER TYPE public.language_enum OWNER TO akul;

--
-- Name: role; Type: TYPE; Schema: public; Owner: akul
--

CREATE TYPE public.role AS ENUM (
    'ADMIN',
    'NO_USER',
    'TEACHER'
);


ALTER TYPE public.role OWNER TO akul;

--
-- Name: role_enum; Type: TYPE; Schema: public; Owner: akul
--

CREATE TYPE public.role_enum AS ENUM (
    'ADMIN',
    'TEACHER'
);


ALTER TYPE public.role_enum OWNER TO akul;

--
-- Name: CAST (public.language AS character varying); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (public.language AS character varying) WITH INOUT AS IMPLICIT;


--
-- Name: CAST (public.role AS character varying); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (public.role AS character varying) WITH INOUT AS IMPLICIT;


--
-- Name: CAST (character varying AS public.language); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (character varying AS public.language) WITH INOUT AS IMPLICIT;


--
-- Name: CAST (character varying AS public.role); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (character varying AS public.role) WITH INOUT AS IMPLICIT;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audios; Type: TABLE; Schema: public; Owner: akul
--

CREATE TABLE public.audios (
    audio_id integer NOT NULL,
    title character varying(255),
    filepath character varying(255),
    song_id integer
);


ALTER TABLE public.audios OWNER TO akul;

--
-- Name: audios_seq; Type: SEQUENCE; Schema: public; Owner: akul
--

CREATE SEQUENCE public.audios_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.audios_seq OWNER TO akul;

--
-- Name: certificates; Type: TABLE; Schema: public; Owner: akul
--

CREATE TABLE public.certificates (
    certificate_id integer NOT NULL,
    creation_date timestamp(6) without time zone,
    file_path character varying(255),
    student_id integer
);


ALTER TABLE public.certificates OWNER TO akul;

--
-- Name: certificates_seq; Type: SEQUENCE; Schema: public; Owner: akul
--

CREATE SEQUENCE public.certificates_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.certificates_seq OWNER TO akul;

--
-- Name: songs; Type: TABLE; Schema: public; Owner: akul
--

CREATE TABLE public.songs (
    song_id integer NOT NULL,
    title character varying(255),
    verse text[],
    language public.language_enum DEFAULT 'TAMIL'::public.language_enum NOT NULL
);


ALTER TABLE public.songs OWNER TO akul;

--
-- Name: songs_audios; Type: TABLE; Schema: public; Owner: akul
--

CREATE TABLE public.songs_audios (
    song_song_id integer NOT NULL,
    audio_audio_id integer NOT NULL
);


ALTER TABLE public.songs_audios OWNER TO akul;

--
-- Name: students; Type: TABLE; Schema: public; Owner: akul
--

CREATE TABLE public.students (
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    student_id integer NOT NULL
);


ALTER TABLE public.students OWNER TO akul;

--
-- Name: students_student_id_seq; Type: SEQUENCE; Schema: public; Owner: akul
--

ALTER TABLE public.students ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: akul
--

CREATE TABLE public.users (
    u_id integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    email character varying(255),
    password character varying(255),
    role public.role_enum NOT NULL,
    is_first_login boolean NOT NULL
);


ALTER TABLE public.users OWNER TO akul;

--
-- Name: users_u_id_seq; Type: SEQUENCE; Schema: public; Owner: akul
--

CREATE SEQUENCE public.users_u_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_u_id_seq OWNER TO akul;

--
-- Name: users_u_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: akul
--

ALTER SEQUENCE public.users_u_id_seq OWNED BY public.users.u_id;


--
-- Name: users u_id; Type: DEFAULT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.users ALTER COLUMN u_id SET DEFAULT nextval('public.users_u_id_seq'::regclass);


--
-- Data for Name: audios; Type: TABLE DATA; Schema: public; Owner: akul
--

COPY public.audios (audio_id, title, filepath, song_id) FROM stdin;
6	song1	song1.mp3	1
7	song2	song2.mp3	2
8	song3	song3.mp3	3
9	song4	song4.mp3	4
10	song5	song5.mp3	5
\.


--
-- Data for Name: certificates; Type: TABLE DATA; Schema: public; Owner: akul
--

COPY public.certificates (certificate_id, creation_date, file_path, student_id) FROM stdin;
1	2025-10-30 19:09:34.767157	sampleCert1.pdf	36
2	2025-10-30 19:09:45.315191	sampleCert2.pdf	36
3	2025-10-30 19:09:50.179782	sampleCert3.pdf	36
4	2025-10-30 19:09:56.068389	sampleCert4.pdf	36
5	2025-11-03 14:41:12.103674	test	37
\.


--
-- Data for Name: songs; Type: TABLE DATA; Schema: public; Owner: akul
--

COPY public.songs (song_id, title, verse, language) FROM stdin;
2	திருவாசகம்	{"மெய்தான் அரும்பி விதிர்விதிர்த்து உன் விரையார் கழற்கு என்","கைதான் தலைவைத்துக் கண்ணீர் ததும்பி வெதும்பி உள்ளம்","பொய்தான் தவிர்ந்து உன்னைப் போற்றி சயசய போற்றி என்னும்","கைதான் நெகிழவிடேன் உடையாய் என்னைக் கண்டுகொள்ளே."}	TAMIL
3	திருவிசைப்பா	{"ஒளிவளர் விளக்கே உலப்பிலா ஒன்றே உணர்வு சூழ் கடந்ததோர் உணர்வே","தெளிவளர் பளிங்கின் திரள்மணிக் குன்றே சித்தத்துள் தித்திக்கும் தேனே","அளிவளர் உள்ளத்து ஆனந்தக் கனியே அம்பலம் ஆடரங்காக","வெளிவளர் தெய்வக் கூத்துகந்தாயைத் தொண்டனேன் விளம்புமா விளம்பே."}	TAMIL
4	திருப்பல்லாண்டு	{"மன்னுக தில்லை வளர்க நம் பத்தர்கள் வஞ்சகர் போய் அகல","பொன்னின் செய் மண்டபத்துள்ளே புகுந்து புவனி யெல்லாம் விளங்க","அன்ன நடை மடவாள் உமைகோன் அடியோமுக்கு அருள் புரிந்து","பின்னைப் பிறவி அறுக்க நெறிதந்த பித்தற்குப் பல்லாண்டு கூறுதுமே."}	TAMIL
5	பெரியபுராணம்	{"உலகெலாம் உணர்ந்து ஓதற்கு அரியவன்","நிலவு உலாவிய நீர்மலி வேணியன்","அலகில் சோதியன் அம்பலத்து ஆடுவான்","மலர் சிலம்படி வாழ்த்தி வணங்குவாம்."}	TAMIL
1	தேவாரம்	{"தோடுடைய செவியன் விடை ஏறி ஓர் தூ வெண்மதி சூடிக்","காடுடைய சுடலைப் பொடி பூசி என் உள்ளம் கவர் கள்வன்","ஏடுடைய மலரான் முனைநாள் பணிந்து ஏத்த அருள் செய்த","பீடுடைய பிரமாபுரம் மேவிய பெம்மான் இவன் அன்றே."}	TAMIL
6	తేవరం	{"తోడుడై షెవియన్ విడై ఏరి లేదా తువెన్ మడిషుడి","కడుదైయా షూడ్లై పొడి పూషి ఎన్ ఉల్లమ్ కావర్కళ్వాన్","ఎదుడే మలరన్ మనైనాల్ పనిండేత్త అరుళ్షెడ్","పిడుడయ్య బిర్మాపురం మేవియ పెమ్మన్ ఇవన్న్రే"}	TELEGU
7	తిరువాచకం	{"మేడన్ అరుంబి విదిర్విదిర్త్తు ఉన్","వీరయ్యర్ కలర్కు ఎన్.ఎస్","కైదాన్ తలైవైట్టు కన్నీరు తడుంబి","వెడుంబి ఉల్లం","పోయి దాన్ తావిర్ట్టు ఉన్నెప్పోత్రి","షే షే పోత్రి అన్నన్","కైదాన్ నెగిల్విడెన్ ఎగిరింది","ఎన్నైక్కండు కొల్లే"}	TELEGU
8	తిరువిశైప్ప	{"ఒలివాల్ర్ విల్క్కే ఉల్ప్పిలా ఒన్రె","ఉన్ర్వు షుల్ కాదండొర్ ఉన్ర్వే","తేలివల్ర్ పళింగిన్ తిరల్మణిక్కున్రే","చిత్తత్తుల్ తిట్టిక్కుమ్ తేనే, అలివల్ర్ ఉల్లత్తు","ఆనందక్కనియే అంబాల అదరంగా","వెలివల్ర్ దెైవక్కుట్టుగండై","తొండనెన్ విళంబుమా విళంబే"}	TELEGU
9	తిరుప్పల్లాండు	{"మన్నుగ్ తిల్లై వళర్గ్ నామ్ భక్తర్గళ్ వంజగర్ పొయ్యగళ్","పొన్నిశెయ్ మందబత్తుల్లే పుగుండు భువని ఎల్లన్విలాంగ్","ఆన్ నాదమ్‌ద్వాల్ ఉమాకోన్","ఆదిముక్కు అరుల్పురిందు, పిన్నై పిర్వి అరుక్క","నేరి తాండ్ పిత్తర్కు పల్లందు కురుదుమే"}	TELEGU
10	పెరియ పురాణం	{"ఉల్గేల ఉనార్ందు ఓదార్కరియవాన్","నిల్వులవియ నీర్మలి వేణియన్","అల్గిల్ షోడియన్ అంబలట్టు అడువాన్","మలర్ శిలంబడి వాల్టి వనంగువం"}	TELEGU
\.


--
-- Data for Name: songs_audios; Type: TABLE DATA; Schema: public; Owner: akul
--

COPY public.songs_audios (song_song_id, audio_audio_id) FROM stdin;
1	6
2	7
3	8
4	9
5	10
6	6
7	7
8	8
9	9
10	10
\.


--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: akul
--

COPY public.students (email, first_name, last_name, student_id) FROM stdin;
studentdemo@g.com	demo	student	36
studenttesting@g.com	testing	student	37
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: akul
--

COPY public.users (u_id, first_name, last_name, email, password, role, is_first_login) FROM stdin;
20	admin	testing	admin@g.com	$argon2id$v=19$m=15360,t=2,p=1$i62rUL3JbtzvRLmIfCHMACHic+nT5vUuSZe9/Id4sEX/CV0Cv6n42SRWYRG5x/bLIkQ3FnXseQNseLLA8rg9tg$9Y2dLpIWTwe1etfHSVN/HL54qJVy4NB5I1ONHyLSodE	ADMIN	f
21	teacher	demo	teacher@g.com	$argon2id$v=19$m=15360,t=2,p=1$JfwDl9By/BSn5bSw4xWCqOffXK2qfhlPHvm4Im0Iwapl90Ute+MmSbmbQ5/o4s5U1EWt7hMcRquM2rX6DlrLDg$s8F1xPGHUE6SDuhGEkfzWsJTJYgLLD+aF69Wux1KW1U	TEACHER	f
\.


--
-- Name: audios_seq; Type: SEQUENCE SET; Schema: public; Owner: akul
--

SELECT pg_catalog.setval('public.audios_seq', 1, false);


--
-- Name: certificates_seq; Type: SEQUENCE SET; Schema: public; Owner: akul
--

SELECT pg_catalog.setval('public.certificates_seq', 1, false);


--
-- Name: students_student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: akul
--

SELECT pg_catalog.setval('public.students_student_id_seq', 37, true);


--
-- Name: users_u_id_seq; Type: SEQUENCE SET; Schema: public; Owner: akul
--

SELECT pg_catalog.setval('public.users_u_id_seq', 21, true);


--
-- Name: audios audios_pkey; Type: CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.audios
    ADD CONSTRAINT audios_pkey PRIMARY KEY (audio_id);


--
-- Name: certificates certificates_pkey; Type: CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT certificates_pkey PRIMARY KEY (certificate_id);


--
-- Name: songs_audios songs_audios_pkey; Type: CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.songs_audios
    ADD CONSTRAINT songs_audios_pkey PRIMARY KEY (song_song_id, audio_audio_id);


--
-- Name: songs songs_pkey; Type: CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.songs
    ADD CONSTRAINT songs_pkey PRIMARY KEY (song_id);


--
-- Name: students students_email_key; Type: CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_email_key UNIQUE (email);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (student_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (u_id);


--
-- Name: audios audios_song_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.audios
    ADD CONSTRAINT audios_song_id_fkey FOREIGN KEY (song_id) REFERENCES public.songs(song_id);


--
-- Name: songs_audios fk8e3pvrcodbjgjmjr23e4tw6ig; Type: FK CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.songs_audios
    ADD CONSTRAINT fk8e3pvrcodbjgjmjr23e4tw6ig FOREIGN KEY (song_song_id) REFERENCES public.songs(song_id);


--
-- Name: songs_audios fkhuvel3ws3inlasdj6qx5mnkj2; Type: FK CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.songs_audios
    ADD CONSTRAINT fkhuvel3ws3inlasdj6qx5mnkj2 FOREIGN KEY (audio_audio_id) REFERENCES public.audios(audio_id);


--
-- Name: certificates fkpc7mh1qdwwhawk8k3d8cw5y19; Type: FK CONSTRAINT; Schema: public; Owner: akul
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT fkpc7mh1qdwwhawk8k3d8cw5y19 FOREIGN KEY (student_id) REFERENCES public.students(student_id);


--
-- PostgreSQL database dump complete
--

